name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  shared_preferences: 2.0.15 
  path_provider: 2.0.8 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  assets:
    - assets/
  uses-material-design: true


  # If you plan to add images, define assets like this:
  # assets:
  #   - assets/images/
