// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_OgLZJhPrQ-mMd2YZUqUKyQegg_AtNos',
    appId: '1:395955687433:web:d5488f11e6cae89021a8d8',
    messagingSenderId: '395955687433',
    projectId: 'myapp-48459',
    authDomain: 'myapp-48459.firebaseapp.com',
    storageBucket: 'myapp-48459.firebasestorage.app',
    measurementId: 'G-MEV83SWEVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJJp8E7rdRP7IM_7uVsFSG3UpAufY5biY',
    appId: '1:395955687433:android:b19c191032c5b10521a8d8',
    messagingSenderId: '395955687433',
    projectId: 'myapp-48459',
    storageBucket: 'myapp-48459.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-INpa6pqsbCfA6rG-jc-QOfl5NJC_T0Q',
    appId: '1:395955687433:ios:875877603b48215e21a8d8',
    messagingSenderId: '395955687433',
    projectId: 'myapp-48459',
    storageBucket: 'myapp-48459.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-INpa6pqsbCfA6rG-jc-QOfl5NJC_T0Q',
    appId: '1:395955687433:ios:875877603b48215e21a8d8',
    messagingSenderId: '395955687433',
    projectId: 'myapp-48459',
    storageBucket: 'myapp-48459.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_OgLZJhPrQ-mMd2YZUqUKyQegg_AtNos',
    appId: '1:395955687433:web:54850470c17448e321a8d8',
    messagingSenderId: '395955687433',
    projectId: 'myapp-48459',
    authDomain: 'myapp-48459.firebaseapp.com',
    storageBucket: 'myapp-48459.firebasestorage.app',
    measurementId: 'G-82DC940R27',
  );
}
